server:
  port: 8000

spring:
  application:
    name: gatewayserverResume
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google_client_id}
            client-secret: ${google_client_secret}
          github:
            client-id: ${git_client_id}
            client-secret: ${git_client_secret}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j.circuitbreaker:
  configs:
    default:
      sliding-window-size: 20
      permitted-number-of-calls-in-half-open-state: 2
      failure-rate-threshold: 50
      wait-duration-in-open-state:
        seconds: 12
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted

frontend:
  url: http://localhost:3000
